Chore: check backup device is mounted as long as config file is present

diff --git a/bin/bakcheck b/bin/bakcheck
--- a/bin/bakcheck
+++ b/bin/bakcheck
@@ -5,7 +5,7 @@ CHECK_DIR=$(pwd)
 
 # Safety check to prevent scanning system files
 if [[ -z "$CHECK_DIR" || "$CHECK_DIR" == "/" ]]; then
-    echo "Error: CHECK_DIR is not set or is root (/), aborting!"
+    echo "Error: Source directory is not set or is root (/), aborting!"
     exit 1
 fi
 
@@ -14,6 +14,12 @@ echo "Checking: $CHECK_DIR"
 # Read backup destination from .bak/.bakconfig
 if [ -f "$CHECK_DIR/.bak/.bakconfig" ]; then
     source "$CHECK_DIR/.bak/.bakconfig"
+    EXPECTED_DEVICE=$(findmnt -rno TARGET -S LABEL="$DEVICE_LABEL" | sed 's/\\x20/ /g')
+    if [ -z "$EXPECTED_DEVICE" ] || [[ "$EXPECTED_DEVICE" != "$MOUNT_POINT"* ]]; then
+        echo "Error: The expected backup device ($DEVICE_LABEL) is not mounted."
+        echo "please mount and try again."
+        exit 1
+    fi
 else
     echo "No configuration file found!"
     echo "Run: bak init"
@@ -22,7 +28,7 @@ fi
 
 # Check if backup destination exists
 if [ ! -d "$BACKUP_DEST" ]; then
-    echo "Backup destination does not exist!"
+    echo "Backup destination path does not exist!"
     echo "Run: bak config set mount </path/to/mount>"
     exit 1
 fi
diff --git a/bin/bakpull b/bin/bakpull
--- a/bin/bakpull
+++ b/bin/bakpull
@@ -6,12 +6,20 @@ TARGET_DIR=$(pwd)
 # Read backup destination from .bak/.bakconfig
 if [ -f "$TARGET_DIR/.bak/.bakconfig" ]; then
     source "$TARGET_DIR/.bak/.bakconfig"
+    EXPECTED_DEVICE=$(findmnt -rno TARGET -S LABEL="$DEVICE_LABEL" | sed 's/\\x20/ /g')
+    if [ -z "$EXPECTED_DEVICE" ] || [[ "$EXPECTED_DEVICE" != "$MOUNT_POINT"* ]]; then
+        echo "Error: The expected backup device ($DEVICE_LABEL) is not mounted."
+        echo "please mount and try again."
+        exit 1
+    fi
 else
     echo "It seems like your source files no longer exist or are corrupted"
     echo "to retrieve all your files"
     echo "Run: bak restore -lost"
     exit 1
 fi
+
+
 
 # Check if backup destination exists
 if [ ! -d "$BACKUP_DEST" ]; then
@@ -23,13 +31,6 @@ fi
 # Log file path
 LOG_FILE=~/BackupVersionControl/restore.log
 
-# echo "Preparing to restore..."
-# TOTAL_SIZE=$(rsync -av --delete --dry-run --no-perms --exclude-from="$BACKUP_DEST/.bakignore" "$BACKUP_DEST/" "$TARGET_DIR/" | grep "total size is" | awk '{print $4, $5}')
-# echo "Estimated backup size: $TOTAL_SIZE"
-
-# Ask for confirmation before restoring
-# read -p "Proceed with restore? (y/N): " confirm
-# if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
     # Log start time
 echo -e "\n$(date '+%Y-%m-%d %H:%M:%S') - Restore Started" | tee -a "$LOG_FILE"
 echo "Source: $BACKUP_DEST" | tee -a "$LOG_FILE"
@@ -37,12 +38,9 @@ echo "Destination: $TARGET_DIR" | tee -a "$LOG_FILE"
 echo "-------------------------------------" | tee -a "$LOG_FILE"
 
 # Perform the actual restore
-# sudo -u "$BACKUP_USER" rsync -av "$BACKUP_DEST/" "$TARGET_DIR/" 2>&1 | tee -a "$LOG_FILE"
 sudo -u "$BACKUP_USER" rsync -av --no-perms --omit-dir-times "$BACKUP_DEST/" "$TARGET_DIR/" 2>&1 | tee -a "$LOG_FILE"
 
 echo "Restore completed: $BACKUP_DEST → $TARGET_DIR" | tee -a "$LOG_FILE"
 echo "-------------------------------------" | tee -a "$LOG_FILE"
 echo "$(date '+%Y-%m-%d %H:%M:%S') - Restore Completed" | tee -a "$LOG_FILE"
-# else
-#     echo "Restore canceled."
-# fi
+
diff --git a/bin/bakpush b/bin/bakpush
--- a/bin/bakpush
+++ b/bin/bakpush
@@ -6,6 +6,12 @@ SOURCE_DIR=$(pwd)
 # Read backup destination from .bak/.bakconfig
 if [ -f "$SOURCE_DIR/.bak/.bakconfig" ]; then
     source "$SOURCE_DIR/.bak/.bakconfig"
+    EXPECTED_DEVICE=$(findmnt -rno TARGET -S LABEL="$DEVICE_LABEL" | sed 's/\\x20/ /g')
+    if [ -z "$EXPECTED_DEVICE" ] || [[ "$EXPECTED_DEVICE" != "$MOUNT_POINT"* ]]; then
+        echo "Error: The expected backup device ($DEVICE_LABEL) is not mounted."
+        echo "please mount and try again."
+        exit 1
+    fi
 else
     echo "There is no configuration file."
     echo "Run: bak init"
@@ -43,13 +49,6 @@ LOG_FILE=$SOURCE_DIR/backup.log
 # Ensure log file exists (optional, for logging clarity)
 touch "$LOG_FILE"
 
-# echo "Preparing to backup..."
-# TOTAL_SIZE=$(rsync -av --delete --dry-run --no-perms --exclude-from="$SOURCE_DIR/.bakignore" "$SOURCE_DIR/" "$BACKUP_DEST/" | grep "total size is" | awk '{print $4, $5}')
-# echo "Estimated backup size: $TOTAL_SIZE"
-
-# Confirm before actual push
-# read -p "Proceed with backup? (y/N): " confirm
-# if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
     # Add timestamp and log header
 echo -e "\n$(date '+%Y-%m-%d %H:%M:%S') - Backup Started" | tee -a "$LOG_FILE"
 echo "Source: $SOURCE_DIR" | tee -a "$LOG_FILE"
@@ -62,6 +61,4 @@ echo "Backup completed Successfully"
 # Log completion time
 echo -e "-------------------------------------" | tee -a "$LOG_FILE"
 echo "$(date '+%Y-%m-%d %H:%M:%S') - Backup Completed" | tee -a "$LOG_FILE"
-# else
-#     echo "Backup canceled."
-# fi
+
